name: Upload filtered XML to GitHub

on:
  schedule:
    - cron: "0 0 * * *"  # Exécution tous les jours à minuit UTC
  workflow_dispatch:  # Exécution manuelle

jobs:
  upload_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the EPG script
        run: python3 epg_script.py  # Assure-toi que le script s'appelle epg_script.py

      - name: Commit and push the changes
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add filtered_epg.xml
          git commit -m "Update filtered EPG"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/d32k18/epg-scraper.git
